name: Azure Project Deployment

on:
    workflow_run:
        workflows: ["Azure Base Infrastructure Deployment"]
        types:
            - completed
    
env:
    AZURE_CREDENTIALS: '{"clientId": "${{secrets.AZURE_CLIENT_ID}}", "clientSecret": "${{secrets.AZURE_CLIENT_SECRET}}", "subscriptionId": "${{secrets.AZURE_SUBSCRIPTION_ID}}", "tenantId": "${{secrets.AZURE_TENANT_ID}}"}'
    AZURE_ENV: ${{vars.AZURE_ENV}}
    PROJECT_NAME: ${{vars.PROJECT_NAME}}
    PROJECT_VERSION: ${{vars.PROJECT_VERSION}}
    LOCATION: ${{vars.LOCATION}}

jobs:
    create_rg:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ env.AZURE_CREDENTIALS }}

            - name: ssh-keygen
              run: |
                  ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
                  does_kv_secret_exist=$(az keyvault secret show --vault-name kv-${{ env.PROJECT_NAME }}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --name ssh-key -o tsv)
                  if [ -z "$does_kv_secret_exist" ]; then
                    az keyvault secret set --vault-name kv-${{ env.PROJECT_NAME }}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --name ssh-key --value "$(cat ~/.ssh/id_rsa.pub)"
                    az keyvault secret set --vault-name kv-${{ env.PROJECT_NAME }}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --name ssh-key-private --value "$(cat ~/.ssh/id_rsa)"
                  fi
            - name: Deploy Resource Group
              run: |
                  az deployment sub create --name 'rg-${{env.PROJECT_NAME}}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }}' --location ${{ env.LOCATION }} --template-file ./Azure/resources/rg.bicep 
                  az deployment group create --resource-group rg-database-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --template-file ./Azure/resources/psql-db.bicep --parameters project_name=${{ env.PROJECT_NAME }} environment=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} adminPassword=${{ secrets.AZURE_DB_PASSWORD }}  
                  az deployment group create --resource-group rg-${{ env.PROJECT_NAME }}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --template-file ./Azure/resources/vm.bicep --parameters project_name=${{ env.PROJECT_NAME }} environment=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} 
                  az deployment group create --resource-group rg-${{ env.PROJECT_NAME }}-${{ env.AZURE_ENV }}-${{ env.PROJECT_VERSION }} --template-file ./Azure/resources/stvm.bicep --parameters project_name=${{ env.PROJECT_NAME }} environment=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} 

            - name : Logout of Azure
              run: |
                  az logout