name: Create Resource Group

on:
    push:
        branches:
            - main
        paths:
            - Azure/**
            - .github/workflows/rg.yml
    pull_request:
        paths:
            - Azure/**
            - .github/workflows/rg.yml
    workflow_dispatch:

env:
    AZURE_CREDENTIALS: '{"clientId": "${{secrets.AZURE_CLIENT_ID}}", "clientSecret": "${{secrets.AZURE_CLIENT_SECRET}}", "subscriptionId": "${{secrets.AZURE_SUBSCRIPTION_ID}}", "tenantId": "${{secrets.AZURE_TENANT_ID}}"}'
    AZURE_ENV: ${{vars.AZURE_ENV}}
    PROJECT_NAME: ${{vars.PROJECT_NAME}}
    PROJECT_VERSION: ${{vars.PROJECT_VERSION}}
    LOCATION: ${{vars.LOCATION}}

jobs:
    create_rg:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: ${{ env.AZURE_CREDENTIALS }}

            - name: Lint Bicep
              run: |
                  az bicep lint --file Azure/resources/rg.bicep

            - name: Bicep Build
              run: |
                  mkdir -p ./Azure/resources/compiled
                  az bicep build --file Azure/resources/rg.bicep --outdir ./Azure/resources/compiled

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rg-artifact-${{ env.PROJECT_NAME }}
                  path: ./Azure/

            - name: Deploy Resource Group
              run: |
                  az deployment sub create --location ${{ env.LOCATION }} --template-file ./Azure/resources/compiled/rg.json --parameters env=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} name='common' --what-if
                  az deployment sub create --location ${{ env.LOCATION }} --template-file ./Azure/resources/compiled/rg.json --parameters env=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} name='network' --what-if
                  az deployment sub create --location ${{ env.LOCATION }} --template-file ./Azure/resources/compiled/rg.json --parameters env=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} name='privatedns' --what-if
                  az deployment sub create --location ${{ env.LOCATION }} --template-file ./Azure/resources/compiled/rg.json --parameters env=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} name='database' --what-if
                  az deployment sub create --location ${{ env.LOCATION }} --template-file ./Azure/resources/compiled/rg.json --parameters env=${{ env.AZURE_ENV }} version=${{ env.PROJECT_VERSION }} name=${{ env.PROJECT_NAME }} --what-if

            - name: Logout of Azure
              run: |
                  az logout

    Checkov_Scan:
        needs: create_rg
        environment: test
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: rg-artifact-${{ env.PROJECT_NAME }}
                  path: ./Azure/

            - name: Checkov Scan (Bicep source)
              uses: bridgecrewio/checkov-action@v12
              with:
                  directory: ./Azure/resources
                  framework: bicep

            - name: Checkov Scan
              uses: bridgecrewio/checkov-action@v12
              with:
                  directory: ./Azure/resources/compiled
                  framework: arm
